DROP TABLE IF EXISTS "User" CASCADE;

CREATE TABLE "User"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserName" varchar(50) NOT NULL,
    "Password" varchar(15) NOT NULL,
    "Role" int NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("ID") 
);
